FROM oven/bun:latest

WORKDIR /app

COPY ./packages  ./packages
COPY ./bun.lock ./bun.lock
COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./apps/contests  ./apps/contests
COPY  ./apps/problems  ./apps/problems
COPY ./apps/utils   ./apps/utils



COPY ./apps/web ./apps/web

RUN bun install
RUN bun run prisma:generate
RUN bun run build



EXPOSE 3000

CMD ["bun", "run", "start:web"]


